BindHost: 127.0.0.1:1010

BaseDirectory: wwwapp

# List of urls to redirect to if request url was `/`
DefaultPages:
  - index.htmlua

# Browsing directories and see files and content of directories
DirectoryBrowsing: false

# Allows to run file without adding .htmlua after filename if set true
ExtentionRequired: false

# Should not include .htmlua after file name if set true and ExtentionRequired should be false to works
NotExtentionInUrl: true

# Connection string vault
ConnectionStrings:
  DefaultContext: 'server=.; database=MyDB; integrated security=true;'

# The target file will execute when ever a request receive
# To prevent render the file requested, must write `return true` in the module
HttpModules:
  SessionManager: '/session_manager.lua'

FrobbidenPaths:
  - Errors/*

Auth:
    Name: 'myapp_session'
    Timeout: '60' # one hour
    Path: '/'
    Key: 'b420c4266590870e8e509595827784f8d6ccc8f7b721b372ceb4af5315b28487'
    DefaultUrl: '/'
    LoginUrl: '/singin'
    RoleManager: 'role_manager.lua'

# Routes
Routes:
  Admin:
    Type: Regex
    Url: '/admin*'
    Route: '/manage/admin-manager.htmlua'
    
  Default:
    Type: Static
    Url: '/css/dynamic.css'
    Route: '/dynamic-css.htmlua'
    
  User:
    Type: Dynamic
    Url: '/admin/{controller}/{action}'
    Route: '/admin/{controller}/{action}.htmlua'

  API:
    Type: Static
    Url: '/api/time'
    Controller: '/api/time.lua'

# Custom error pages
ErrorPages:
  404: /Errors/404.htmlua
  500: /Errors/500.htmlua
