# List of urls to redirect to if request url was `/`
DefaultPages:
  - index

# Allows to run file without adding .htmlua after filename if set true
ExtentionRequired: false

# Should not include .htmlua after file name if set true and ExtentionRequired should be false to works
NotExtentionInUrl: true

# Connection string vault
ConnectionStrings:
  DefaultContext: 'server=.; database=MyDB; integrated security=true;'

# Routes
Routes:
  admin:
    type: regex
    url: '/admin*'
    route: '/manage/admin-manager.htmlua'
    
  default:
    type: static
    url: '/css/dynamic.css'
    route: '/dynamic-css.htmlua'
    
  product:
    type: multiple
    url: '/product/{action}'
    route: '/product/{action}.htmlua'
    default: '/product/list.htmlua'

# Custom error pages
ErrorPages:
  404: /Error/404.htmlua
  500: /Error/500.htmlua
