//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 987654321.
        /// </summary>
        internal static string CertificationPassword {
            get {
                return ResourceManager.GetString("CertificationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Module options:
        ///local always_try_using_lpeg = true
        ///local register_global_module_table = false
        ///local global_module_name = &apos;json&apos;
        ///
        ///--[==[
        ///
        ///David Kolf&apos;s JSON module for Lua 5.1/5.2
        ///
        ///Version 2.5
        ///
        ///
        ///For the documentation see the corresponding readme.txt or visit
        ///&lt;http://dkolf.de/src/dkjson-lua.fsl/&gt;.
        ///
        ///You can contact the author by sending an e-mail to &apos;david&apos; at the
        ///domain &apos;dkolf.de&apos;.
        ///
        ///
        ///Copyright (C) 2010-2014 David Heiko Kolf
        ///
        ///Permission is hereby granted, free of charge, to any person ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dkjson {
            get {
                return ResourceManager.GetString("dkjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;lrt&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Not found&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            text-align: center;
        ///        }
        ///
        ///        h1 {
        ///            color:rgb(107, 18, 190)
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Error: The request url &quot;{Url}&quot; was not found!&lt;/h1&gt;
        ///    &lt;hr&gt;
        ///    &lt;p class=&quot;exception-message&quot;&gt;&lt;span style=&quot;font-weight: bold&quot;&gt;Description:&lt;/span&gt; {D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Http404 {
            get {
                return ResourceManager.GetString("Http404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; dir=&quot;lrt&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;{Error}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body,html{height:100%}h1{color:red;margin-top:1rem;margin-bottom:0.5rem;font-size:2.5rem}p{font-size:18px}.exception-type{margin-top:0}.exception-message{font-size:1.5rem}pre{background-color:#ffb;border:1px solid #f99;font-size:18px;padding:1.5rem 1rem}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;{Error}&lt;/h1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Http500 {
            get {
                return ResourceManager.GetString("Http500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local mssql = { version = &quot;1.0&quot; }
        ///
        ///-- Create connection
        ///function mssql.createConnection(connectionString)
        ///    local connection = {}
        ///    connection.context = create_mssql_connection(connectionString)
        ///
        ///    function connection:executeScalar(query)
        ///        local command = self.context:CreateCommand()
        ///        command.CommandText = query
        ///        result = command:ExecuteScalar()
        ///        return result
        ///    end
        ///
        ///    function connection:open()
        ///        self.context:Open()
        ///    end
        ///
        ///    function connect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mssql {
            get {
                return ResourceManager.GetString("mssql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
